// Generated by Wrangler
// Runtime types generated with workerd@1.20251217.0

declare namespace Cloudflare {
  interface Env {
    UUID: string;
    PROXYIP: string;
  }
}
interface Env extends Cloudflare.Env {}
